### ISSUE TITLE
Add a search engine

### ISSUE THREAD

**Issue by marcospozzo** [marcospozzo/partitasmusic#2]
On views -> partials -> sidebar.ejs there is a search box commented out. It would be a good improvement to have it working so users could write a piece name/author and a page with results show up.

**Comment by arzezak** [comment]
I'd love to help but it's really hard to contribute without DB mocks or some sort of script to seed a local subset of contributors/contributions. Please consider adding those.

💪 Thank you Marcos!

**Comment by marcospozzo** [comment]
Hey Ariel, great to hear from you!
Would a MongoDB Atlas cloud sample with a few mock entries be enough? Otherwise I'd have to work on a MongoDB local mock and I don't have time to implement this at the moment.
Best,
Marcos.

**Comment by arzezak** [comment]
That'll do: A `testing` env.

**Comment by marcospozzo** [comment]
Hey @arzezak! I just finished creating the mongodb mock.

Steps are:

1. Go to develop branch
2. Go to app.js file. On line 17, replace DB_CONNECT with DB_CONNECT_TEST
3. On the .env-sample file you can find the corresponding environment variable to replace locally

If you have any questions please let me know.
Apologies for the delay!
Best,
Marcos.

**Comment by marcospozzo** [comment]
Won't be needing this feature for the moment!

**Comment by marcospozzo** [comment]
Hey @arzezak! I'm reopening this one.

I am redesigning a few pages of the website and I think the search box is a nice to have feature.

> On views -> partials -> sidebar.ejs there is a HTML search box commented out.

I'm also available for working together on this if you'd like to!

**Comment by marcospozzo** [comment]
Done! [d1f68c4](https://github.com/marcospozzo/partitasmusic/commit/d1f68c49573d2ba28fc448918f402069cc99af94)
